### ISSUE TITLE
Mtga Tool isn't working

### ISSUE THREAD

**Issue by AndreaMTG** [mtgatool/mtgatool-desktop#60] opened 2023-08-17 08:40 UTC
Hello there,  I'm writing this post because the tracker isn't working for me until last update. The problem is the follow... when I double click the mtga tool icon it launches the "checking for updates " message and it immediately opens the window related to my account so it doesn't permit me to type any password. The worst thing is it doesn't work at all because if I try to click every tab  (my decks, history etc...) it doesn't show anything, even the options section has the same problem. Maybe it could be an update bug? Thanks in advance for your help and good work.

**Comment by riQQ** [comment] 2023-08-17 18:41
Duplicate of #59

**Closed by riQQ** 2023-08-17 18:41 UTC
Labels: Bug, Priority
