### ISSUE TITLE
Unable to change Cards Data language

### ISSUE THREAD

**Issue by xiaop3344** [mtgatool/mtgatool-desktop#23] opened 2022-04-09 07:44 UTC
I change the cards Data language to Chinese,but not work.
Restart app ,the About shows Metadata is v136(EN).
But,I try use WEB tools is working , could change language.

**Comment by bluehysteric** [comment] 2022-04-17 02:13
It does not show Chinese

**Comment by Manwe-777** [comment] 2022-07-29 14:19
Duplicate of #9

**Closed by Manwe-777** 2022-07-29 14:19 UTC
