### ISSUE TITLE
Chinese cards data failed

### ISSUE THREAD

**Issue by Elio-zhy** [mtgatool/mtgatool-desktop#22] opened 2022-03-30 02:34 UTC
I choose Chinese but it still shows English card information.
Wondering how to solve it. Thanks.

**Comment by bluehysteric** [comment] 2022-04-17 02:13
It does not show Chinese

**Comment by Manwe-777** [comment] 2022-07-29 14:20
Duplicate of #9

**Closed by Manwe-777** 2022-07-29 14:20 UTC
